### ISSUE TITLE
Fall 2022 planning

### ISSUE THREAD

**Issue by jayhesselberth** [MOLB7950/MOLB7950-website#10]
## Schedule

- [Fall 2022 Academic calendar](https://www.ucdenver.edu/docs/librariesprovider122/academic-calendars/fall-2022-printable.pdf)
- Start: Aug 22
- Finals: Dec 12-17
- Holidays: Sept 5, Nov 21-27

**Comment by jayhesselberth** [comment]
```yaml
lessons:

  - title: "**Week 01: Bootcamp**"
  - date: "Mon, Aug 17"
    title: "Bootcamp: Shell"
    instructor: "Hesselberth"
  - date: "Tues, Aug 18"
    title: "Bootcamp: Shell"
    instructor: "Hesselberth"
  - date: "Wed, Aug 19"
    title: "Bootcamp: Shell"
    instructor: "Hesselberth"
  - date: "Thurs, Aug 20"
    title: "Bootcamp: Shell"
    slides: ""
    instructor: "Hesselberth"
  - date: "Fri, Aug 21"
    title: "Bootcamp: Shell"
    instructor: "Hesselberth"

  - title: "**Week 02: Bootcamp**"
  - date: "Mon, Aug 24"
    title: "Bootcamp: R"
    instructor: "Jagannathan"
  - date: "Tues, Aug 25"
    title: "Bootcamp: R"
    instructor: "Jagannathan"
  - date: "Wed, Aug 26"
    title: "Bootcamp: R"
    instructor: "Jagannathan"
  - date: "Thurs, Aug 27"
    title: "Bootcamp: R"
    instructor: "Jagannathan"
  - date: "Fri, Aug 28"
    title: "Bootcamp: R"
    instructor: "Jagannathan"

  - title: "**Week 03: Bootcamp**"
  - date: "Mon, Aug 31"
    title: "Bootcamp: Python"
    instructor: "Ramachandran"
  - date: "Tues, Sept 1"
    title: "Bootcamp: Python"
    instructor: "Ramachandran"
  - date: "Wed, Sept 2"
    title: "Bootcamp: Python"
    instructor: "Ramachandran"
  - date: "Thurs, Sept 3"
    title: "Bootcamp: Python"
    instructor: "Taliaferro"
  - date: "Fri, Sept 4"
    title: "Bootcamp: Python"
    instructor: "Taliaferro"

  - title: "**Week 04: Bootcamp**"
  - date: "Mon, Sept 7"
    title: "**No class: Labor Day Holiday**"
  - date: "Tues, Sept 8"
    title: "Bootcamp: Statistical Concepts"
    instructor: "Ramachandran"
  - date: "Wed, Sept 9"
    title: "Bootcamp: Statistical Concepts"
    instructor: "Mukherjee"
  - date: "Fri, Sept 11"
    title: "Bootcamp Review (optional)"

  - title: "**Week 05: DNA Block**"
  - date: "Mon, Sept 14"
    title: "Genome Sequencing"
    instructor: "Hesselberth"
  - date: "Wed, Sept 16"
    title: "Genome Sequencing"
    instructor: "Hesselberth"
  - date: "Fri, Sept 18"
    title: "ChIP-seq"
    instructor: "Ramachandran"

  - title: "**Week 06: DNA Block**"
  - date: "Mon, Sept 21"
    title: "ChIP-seq"
    instructor: "Ramachandran"
  - date: "Wed, Sept 23"
    title: "ChIP-seq"
    instructor: "Ramachandran"
  - date: "Fri, Sept 25"
    title: "Chromatin accessibility"
    instructor: "Ramachandran"

  - title: "**Week 07: DNA Block**"
  - date: "Mon, Sept 28"
    title: "Chromatin accessibility"
    instructor: "Ramachandran"
  - date: "Wed, Sept 30"
    title: "Chromatin accessibility"
    instructor: "Ramachandran"
  - date: "Fri, Oct 2"
    title: "DNA Block Review (optional)"
    instructor: "Hesselberth/Ramachandran"

  - title: "**Week 08: RNA Block**"
  - date: "Mon, Oct 5"
    title: "RNA-seq Basics"
    instructor: "Mukherjee"
  - date: "Wed, Oct 7"
    title: "Differential Gene Expression"
    instructor: "Taliaferro"
  - date: "Fri, Oct 9"
    title: "Differential Gene Expression"
    instructor: "Taliaferro"

  - title: "**Week 09: RNA Block**"
  - date: "Mon, Oct 12"
    title: "Alternative Splicing"
    instructor: "Taliaferro"
  - date: "Wed, Oct 14"
    title: "Alternative Splicing"
    instructor: "Taliaferro"
  - date: "Fri, Oct 16"
    title: "Alternative Splicing"
    instructor: "Taliaferro"

  - title: "**Week 10: RNA Block**"
  - date: "Mon, Oct 19"
    title: "RNA binding protein-RNA interactions"
    instructor: "Mukherjee"
  - date: "Wed, Oct 21"
    title: "RNA binding protein-RNA interactions"
    instructor: "Mukherjee"
  - date: "Fri, Oct 23"
    title: "Ribosome Profiling"
    instructor: "Mukherjee"

  - title: "**Week 11: RNA Block**"
  - date: "Mon, Oct 26"
    title: "Single-cell mRNA sequencing"
    instructor: "Riemondy"
  - date: "Wed, Oct 28"
    title: "Single-cell mRNA sequencing"
    instructor: "Riemondy"
  - date: "Fri, Oct 30"
    title: "Block RNA Review (Optional)"
    instructor: "Mukherjee/Taliaferro/Riemondy"
  - title: "**Week 12: Protein Block**"
  - date: "Mon, Nov 2"
    title: "Protein identification and sequence databases"
    instructor: "Lam"
  - date: "Tues, Nov 3"
    title: "**GO VOTE**"
  - date: "Wed, Nov 4"
    title: "Quantitative mass spectrometry and analysis"
    instructor: "Lam"
  - date: "Fri, Nov 6"
    title: "Protein networks and visualization"
    instructor: "Lam"

  - title: "**Week 13: Protein Block**"
  - date: "Mon, Nov 9"
    title: "Protein Sequence and Domain Analysis"
    instructor: "Hesselberth"
  - date: "Wed, Nov 11"
    title: "Multiple Sequence Alignments"
    instructor: "Hesselberth"
  - date: "Fri, Nov 13"
    title: "Block Protein Review (Optional)"

  - title: "**Week 14: Final Projects**"
  - date: "Mon, Nov 16"
    title: "Student Presentations"
  - date: "Wed, Nov 18"
    title: "Student Presentations"
  - date: "Fri, Nov 20"
    title: "Student Presentations"

```
